### ISSUE TITLE
[KR] V26 malfunction

### ISSUE THREAD

**Issue by revi** [kshman/DutyContent#116]
V26 출시 후부터 실제 매칭되는 던전과 상관없이 `0` 던전으로 안내되고 있습니다.

![image](https://user-images.githubusercontent.com/7630875/188313191-0150ee6c-84e3-425c-87c3-ed8e708b680c.png)
(맨 마지막에 실제로 로딩된 던전: 
![image](https://user-images.githubusercontent.com/7630875/188313228-b328b5e6-fd30-4572-9965-9e32e28146a8.png)
)

(제가 v24 직후부터 오늘까지 정량제였어서 확인이 늦었네요...)

- PS: 커스텀패킷은 Duty Match Instance 값이 확인되지 않습니다.

**Comment by revi** [comment]
[디스코드](https://discord.gg/8h8h5EwDGq)에서 제보받은 사진 추가해 둡니다.

|스크린샷|설정|
|---|---|
|![image](https://user-images.githubusercontent.com/7630875/188313510-3c441538-f068-482d-8ec1-9ad2fa2850fb.png)|![image](https://user-images.githubusercontent.com/7630875/188313516-0a244e11-dbda-47e5-9157-8249776700b0.png)|

**Comment by kshman** [comment]
헉... 제가 결재 해보고 테스트해보겠습니다 ㅠ

**Comment by kshman** [comment]
테스트로 칵밧에서 리전 검사하는 것만 넣고 패킷을 재탐색해보니
![image](https://user-images.githubusercontent.com/7216647/189798317-5d8ea136-cb09-4ec9-be69-d87dfedcc07f.png)

잘 동작하는 걸로 보입니다 혹시 괜찮으시면 아래 패킷으로 테스트 몇번 부탁드릴 수 있을까요

```
# DutyPacket configuration: 2022-09-13 오전 11:58:43

# packet
Version=1220913
Description=Custom (2022-09-13)
OpFate=309
OpDuty=758
OpMatch=346
OpInstance=338
OpZone=470
OpSouthernBozja=0
```

감사합니다~

**Comment by kshman** [comment]
참고로 매칭 메시지가 두번 오는데, 이건 좀 봐야겟습니다.
아니면 6.2 패킷때 이 부분 해결했는데, 6.2 아직 좀 남았겠죠....

**Comment by kshman** [comment]
아. 짐 6.05 패킷 올려주신걸 보니 똑같네요;;;;

아마 올려주신 스샷의 오류는 새로 추가했던 체크 박스를 안눌러서 그런걸로 보입니다.
리전 검사를 내부에 추가해 액토즈판 실행 중인지 확인하도록 변경했으니 문제가 해결될걸로 기대합니다

버전 27 올리겠습니다 ㅠ

**Comment by kshman** [comment]
고치는 김에 메시지 두번 오던거 한번만 오게 했어요

**Comment by revi** [comment]
v27 올리니 인스턴스 인식은 잘 되네요. 그러나... 투신 오딘 토벌전을 인식 못 하고 있네요.... 구 방어전도 인식 안 하고요. Zone/FATE 는 인식 됩니다.

![image](https://user-images.githubusercontent.com/7630875/189885598-ad23d114-fc40-4a23-8346-10faaff5342e.png)
![image](https://user-images.githubusercontent.com/7630875/189885889-2e2d9383-87de-4d6f-ab98-9d86fbe244d0.png)
![image](https://user-images.githubusercontent.com/7630875/189886021-9f52d632-2972-4965-b563-0b694a8400fd.png)

**Comment by kshman** [comment]
패킷....파인더죠. 멘트를 수정을 안했네요.
6.2부터 전에 쓰던 인스턴스들이 사라져서 점검용 인스를 파이널 스텝스 오브 페이트(니드헤그 토멸전)로 바꿨습니다.

패치 로그는 잘 써놨는데, 언어 멘트 수정을 안했네요. 고쳐 놓을께요. 😭

**Comment by kshman** [comment]
![image](https://user-images.githubusercontent.com/7216647/190032122-85c9e226-2a5e-4aa1-b50a-4ba12496ea4d.png)

**Comment by revi** [comment]
![image](https://user-images.githubusercontent.com/7630875/193848122-1d0bb233-9a43-4847-acb2-2fcd95708a0d.png)

바로지난패치까지는 ACT OpCodes와 무관하게 커스텀패킷 긁어올 수 있었는데 이번에는 또 안되네요... 여름여울에서도 코드 못 긁어오더라고요. 제가 지금 마침 정액제가 오늘 끊겨서 정량제라서... 내일이나 모레쯤 정액제 다시 긁긴 하겠지만요.

**Comment by kshman** [comment]
이번 액토즈판 버전이 몇이죠
이쪽 6.2에서 구조가 변경됐는데, 액토즈판에는 바로 적용됐을 가능성도 있네요.
시간날때 한번 들어가 보겠습니다

**Comment by kshman** [comment]
한쿡판 패킷에 특이점이 있나 본데요... 
깔아보고 테스트할께요.

컴터 바꾸고 안깔았....

**Comment by kshman** [comment]
들어가서 해봤는데 패킷 잘 잡힙니다. 안잡힌다고 해서 쫄아서 디버그 키고 봤는데
그냥 되네요. 보즈야 패킷은 못했고... 일단 적용해놨습니다

```
# DutyPacket configuration: 2022-10-06 오전 1:56:11

# packet
Version=5006100
Description=6.1 (한국판)
OpFate=649
OpDuty=548
OpMatch=288
OpInstance=880
OpZone=460
OpSouthernBozja=0
```

**Comment by revi** [comment]
머쓱타드... 일이 바빠서 보즈야 패킷은 내일쯤 해서 올릴게요. (제가 최근에 듀티콘 빼고 업뎃을 하나도안해서 뭐가 삑사리낫을지도 몰겟네요)

PS: PR 머지권한 혹시 주실 수 있나요...? 어짜피 KR서버 패킷만 건드릴 건데 매번 PR 기다리기보다는 바로 머지하는 게 빠를 거 같아서요 (...).

일단 티켓은 닫겠습니당~
