### ISSUE TITLE
DutyContent.config 파일 위치 수정

### ISSUE THREAD

**Issue by revi** [kshman/DutyContent#117]
>On 2022-08-29 (Mon) 20:21:26+09:00, 해루 <REDACTED> wrote:
>
> 만약 가능하시다면 DutyContent.config 파일을 AppData\Roaming\Advanced Combat Tracker\Config 폴더에 생성하고 플러그인이 인식하도록 변경할 수는 없는지 여쭤보실 수 있을까요?
>
>해당 플러그인은 설정 파일이 플러그인 dll 파일과 동일한 경로에 생성되는 바람에 업데이트할 때마다 초기화되는 상황인 것 같습니다.
>
>해루봇은 덮어쓰기로 업데이트를 하지 않고, 폴더를 완전히 제거한 후 새로운 파일을 받아 압축을 해제하는 방식을 취하고 있습니다. 
>이 방식의 장점은 잔여 파일에 대한 오류가 없어 안전한 업데이트가 가능합니다. 이미 OverlayPlugin과 Hojoring 때문에 오랫동안 이어진 방식입니다. 
>반면 단점은 DutyContent의 config 파일처럼 삭제하지 않아야 하는 파일까지 삭제해서 초기화를 시켜버린다는 것입니다.
>예전 cactbot 유저 폴더 생각하시면 됩니다. 
>
>어쨌든 해루봇에서 cactbot 유저 폴더 경로를 변경하는 것처럼 조정을 해도 좋지만, 이미 ACT에서 설정 파일을 넣으라고 구축해둔 경로가 있는데 이 경로를 마다할 이유는 없다고 생각합니다.
>해루봇에서도 백업 시 예외를 생각하지 않아도 되는 점도 이점이라고 생각해요.
>
>한번 여쭤 보시고 답변 주시면 감사하겠습니다~

갠적으로 이슈 116 관련해서 물어볼 때 같이 물어보려고 햇는데 답이 없으셔서 이슈 등록해 둡니다.

**Comment by kshman** [comment]
알겠습니다. 어케할지 좀 고민해볼께요.
요즘 바뻐서 레이드도 못하고 있... 😭

**Comment by kshman** [comment]
![image](https://user-images.githubusercontent.com/7216647/189805988-4993bd5a-0244-4a26-a82b-c2a599064804.png)

설정 파일이 원래 위치에 있으면 그걸 읽고, 
설정이 갱신되면 새로 AppData/Config에 넣도록 해봤습니다

참고로 설계 컨셉이, 플러그인 Data는 사용자가 원하는 대로 수정하고 추가하게 되어 있어 config 파일 외에는 옮기기가 힘듬미다. 😭

**Comment by revi** [comment]
v27에서 `%APPDATA%\Roaming\Advanced Combat Tracker\Config` 에 설정값 이전되는 것 정상적으로 확인했습니다 :D
