### ISSUE TITLE
Support Discord Webhook as a notification method

### ISSUE THREAD

**Issue by revi** [kshman/DutyContent#19]
Discord Webhook is far more intuitive for end-user to create and use, compared to Telegram (which requires end-users to perform some advanced method to hook up API directly, either through another bot or directly connecting to API) or Line (which requires working with outside websites to function). Discord requires single URL, which can be created inside the app.

[Discord Docs](https://discord.com/developers/docs/resources/webhook#execute-webhook).

<details>
  <summary>한국어</summary>
  
디스코드 웹훅이 텔레그램(이용자가 다른 봇을 사용하던가, API를 직접 호출하는 방식으로 API에 직접 호출을 해야 함) 또는 Line (앱 외부 사이트를 연결해야 함)에 비해 훨씬 최종 이용자에게 직관적이고 편리한 방식이라고 생각됩니다. (앱 내에서 생성할 수 있는 URL 한 개만 있으면 되므로 텔레그램이나 라인보단... 간편한 편이죠)
</details>

**Comment by kshman** [comment]
Thanks for the suggestion 🥰
I'll read the docs 1st 😵

**Comment by kshman** [comment]
요청하신 기능이 아래처럼 나오는게 맞나요

![image](https://user-images.githubusercontent.com/7216647/122669185-230b4300-d1f7-11eb-99a7-52a5ea777568.png)

![image](https://user-images.githubusercontent.com/7216647/122669245-58b02c00-d1f7-11eb-9dd5-51dbd8416f88.png)

**Comment by kshman** [comment]
https://github.com/kshman/DutyContent/releases/tag/12

**Comment by revi** [comment]
> 요청하신 기능이 아래처럼 나오는게 맞나요

네 맞습니다!

**Comment by kshman** [comment]
적용해놨습니다~ 🥰
