### ISSUE TITLE
Concerning client version differences (SQEX / CN / KR) and auto-update

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [kshman/DutyContent#3]
There are three different version game clients. And the opcode is different for each client.
파판은 세가지 게임 버전으로 서비스 되고 있고, 각자 opcode가 다릅니다.
To support each game client, I suggest to have three different opcode data set in `DutyPacket.config`. And have some option in plugin setting. Like this.
각 게임 클라이언트를 모두 지원하기 위해, `DutyPacket.config`에 opcode 데이터셋을 3가지로 나눠서 저장하면 좋겠다고 생각해요. 그리고 플러그인 설정에는 아래 이미지와 같은 옵션이 있으면 좋겠어요.
![K-007](https://user-images.githubusercontent.com/4695371/120900306-1c18f800-c66f-11eb-98dc-eb40c30f0186.png)

If user set region to `Korean`, load Korean opcode data from `DutyPacket.config` and if user use packet finder and change the opcode list, apply them to `Korean` data set and leave unchanged to other opcode data.
만약 사용자가 `Korean` 클라이언트로 설정하면 `DutyPacket.config`에서 한국어 opcode 데이터를 가져오고 만약 패킷 찾기로 opcode 정보를 변경한다면, `Korean` 데이터셋에 변경사항을 저장하고 다른 지역 값은 그대로 두는거죠.

I'm suggesting this for later suggestion, auto update opcode thing. I saw the config files and data files have version / changed date data inside.
이 기능을 제안하는데는 또 다른 이유가 있습니다. opcode를 서버에서 자동으로 받아오면 좋겠다고 생각해서요. 지금은 release에 config 파일을 개별적으로 업로드하고 유저가 그것을 받아서 설정하는 방식으로 활용되고 있는데요. 그 config 파일과 게임 데이터가 저장된 data 파일이 버전이나 변경된 날짜 정보를 안에 갖고 있는 것을 확인했습니다.
packet config: `# DutyPacket configuration: 2021-06-05 오후 9:38:19`
game data: `"version": "202102171",`
We could get latest data for packet config and game data from the Github repository. If the local data is older than the remote data, update it.
개선하자면 패킷 config 파일과 게임 데이터 파일을 Github 저장소에서 받아온 뒤에, 버전 정보를 비교해서 로컬 데이터가 낡은 경우에는 원격 저장소에 있는 데이터로 업데이트하게 하는 방식이죠. 

이 개선안을 적용하기 전에 서버별로 나누는 작업이 있어야 할 것 같다고 생각합니다. 한국 서버 유저가 이 프로그램을 사용하다가 글섭 데이터로 자동 업데이트되어 갑자기 작동을 안하게 되는 일이 있을 수 있으니까요. 물론 다시 패킷정보를 찾으면 되겠지만 사용자는 왜 그런일이 발생하는지 의문을 갖고 뭐.. 불편할테니까요.

**Comment by Jaehyuk-Lee** [comment]
과거 DFAssist에 업데이터를 내장해서 게임 데이터는 서버에서 가져오는 방식을 활용해 프로그램 릴리즈 주기를 줄인 적이 있습니다https://github.com/Jaehyuk-Lee/DFAssist/blob/master/App/Updater.cs
제가 개발했던건 아니지만 DFAssist를 이어서 개발하다보니 프로그램 구조는 알게 되어서 DutyContent에도 적용할 수 있다는 생각이 들어서요.

**Comment by kshman** [comment]
사실 이건 개인적으로 ACTDFA 도와주다가 패킷 찾기 귀찮아서 시작한 프로젝트입니다
여기 찾아서 오실 분들이라면 스스로 패킷 찾기는 하겠지 생각했습니다

패킷 데이터 분리건은...  일단 건드려볼까요
셀프업뎃은 링크보고 확인부터 해볼께요

감사합니다
