### ISSUE TITLE
System.IO.FileLoadException: Plugin Initialization Failed

### ISSUE THREAD

**Issue by revi** [kshman/DutyContent#35]
![image](https://user-images.githubusercontent.com/7630875/129604750-78f389e8-f3cf-4224-8e78-c739fcfaeb6d.png)

이후 ACT에서 듀티콘텐츠가 로딩되지 않습니다.

다른 문제가 있어서 버그리포트 쓰러 왔다가 새 릴리즈 (18) 있길래 올렸다가 듀티콘텐츠가 사라져버렷네요.

**Comment by revi** [comment]
버전 17까지는 문제없이 실행되었습니다. 버전 18 업데이트 이후부터 터집니다.

**Comment by kshman** [comment]
DutyContent 에러...겠죠. 메시지 박스 내용이 알기 어렵습니다만.

혹시 FFXIV 플러그인 한국어 버전이랑 해보신거죠?
이번에 플러그인 SDK를 업데이트한거랑 충돌이 아닐까도 싶습니다

https://github.com/kshman/DutyContent/releases/tag/18-prevsdk

이걸로 한번 테스트해봐주세요
감사합니다

**Comment by kshman** [comment]
ACT에 한국어 플러그인 넣고 해봤더니 재현되네요
![image](https://user-images.githubusercontent.com/7216647/129618323-06758c51-ad77-44e9-b495-420c28b2b269.png)

위에 링크꺼 넣으시면 실행됩니다
![image](https://user-images.githubusercontent.com/7216647/129618390-86a18010-c69b-4a7f-935a-c66ddcbf3c27.png)

기존 SDK로 롤백해놓을께요

**Comment by kshman** [comment]
버전 19로 업데이트하면 실행에는 문제가 없을거예요.
다른 버그가 보이면 부디 이야기해주세요

감사합니다

**Comment by revi** [comment]
v19에서 실행되는 것 확인했습니다. 원래 리포트하려던 버그가 19에서 재현되면 새 이슈로 올리겠습니다. 감사합니다.

**Comment by kshman** [comment]
윈도우를 리셋했더니 설치되어 있던 한국어 클라이언트가 동작을 안해서 테스트를 못했는데
엊그제 업데이트로 패킷 바뀌지 않았을까요?

그리고 새로 추가한 지역 정보(Zone)도 없어서 맵 로딩 후 페이트 정보가 깜빡이는 현상이 보이실거예요
Zone 정보가 없으면 FFXIV 플러그인 정보로 갱신하는데, 이 정보는 늦게 도달하므로 그렇습니다
