### ISSUE TITLE
DutyContent not reporting duty/FATE after 2021-08-12 hotfix

### ISSUE THREAD

**Issue by revi** [kshman/DutyContent#37]
#35 에서 리포트하려던 버그입니다.
지난 주 목요일(12일)경 신규서버 오픈한다고 [hotfix](http://www.ff14.co.kr/news/notice/view/1960) 하더니 듀티콘텐츠가 새 임무/돌발 알림을 안 주네요.

12일 오전 시간까지 피로스 돌발 알림 잘 뜨다가 목욜 이후 갑자기 임무가 하나도 안 뜨시는 걸 보실 수가 있습니다. 물론 저는 하루도 빼놓지 않고 피로스를 갔습니다. 사스타샤는 오늘 새벽에 부대 비공정 일 시키러 갔더니 비공정 완료알림에 사스타샤 알림이 뜨더라고요. 19 올리고 디버그 켜고 피로스 들어왔는데도 피로스 토끼알림이 안 뜨고 있네요. 로그의 디버그도 한 줄 안 뜹니다.

![image](https://user-images.githubusercontent.com/7630875/129620771-344f13a6-deb9-4781-a99d-4d85969c6b52.png)

**Comment by kshman** [comment]
앞에 이슈에 사족 단 내용의 연장이네요
이번 패치 후 패킷 데이터가 변경되서 그렇습니다.

혹시 가능하시면, 듀티 탭의 커스텀 패킷 한번 해보시면 어떨까요

제가 하자니, 속도 문제로 한국어 클라이언트 설치하는데 시간이 좀 걸리거든요... 😭

**Comment by kshman** [comment]
세이브더퀸 콘테츠를 빼고 나머지는 찾아서 업로드 해놨습니다
크리티컬인게이지먼트(아마 비상교전) 만 빼고 나머지는 동작할겁니다
에우레카도 될거예요

OpFate=174
OpDuty=884
OpMatch=138
OpInstance=329
OpZone=943
OpSouthernBozja=0

**Comment by kshman** [comment]
Plugin Listing에서 Enable을 껏다 다시 켜보세요
![image](https://user-images.githubusercontent.com/7216647/129628999-4b0ca0e2-a7e7-4218-9e07-d76588a5332b.png)

**Comment by kshman** [comment]
뭐 좋은거 주는 줄 알았는데 MGP군요... 시무룩
![image](https://user-images.githubusercontent.com/7216647/129629281-155c007c-0d71-4f85-bd9e-602485e00bc4.png)

**Comment by revi** [comment]
앗... 돌발 한사발 뛰고오니 그새... 감사합니다. 커스텀 패킷은 저번에 한번 시도해봤었는데 돌발이나 매칭 돌렸는데도 아무것도 안 나오길래 뭔가 잘못하고있나 싶어서 포기했었거든요.

알림은 두배로 오지만 일단은 안 오는 게 해결된 거로 만족하고 저는 일단 잠을 좀 자겠습니다 ㅇ<-<

<img width="499" alt="image" src="https://user-images.githubusercontent.com/7630875/129642330-cc2e8dbf-5f09-48c9-a203-1b99d111d85a.png">

**Comment by kshman** [comment]
![image](https://user-images.githubusercontent.com/7216647/129655019-c5f879c5-eea9-494d-9b44-16c697465a47.png)

한국어판 요금문제로(?) 나중에 테스트해보겠습니다...

**Comment by revi** [comment]
ACT 껐다 켜니 알림 한 번 제대로 오네요! 감사합니다.

**Comment by kshman** [comment]
다행입니다 🥰
