### ISSUE TITLE
Zadnor Skirmish Alarm Issue

### ISSUE THREAD

**Issue by ForestBurn** [kshman/DutyContent#49]
![이미지_2021-11-08_025027](https://user-images.githubusercontent.com/30828636/140655991-d396b219-2813-4b5b-9dec-88663d96384a.png)
자트노르 고원을 하던 도중 위와 같은 콘텐츠 알람이 뜨면서 사라지지 않더라고요.

json 파일을 확인해보니 해당 돌발교전 정보가 누락되어있었습니다.
![이미지_2021-11-08_025126](https://user-images.githubusercontent.com/30828636/140656024-601252a9-8566-40e8-970a-c3fd37a1fcec.png)

돌발 아이디: 1729
영어명: Tanking Up
독일어명: Energie für Seiryu Zwo
일어명: 疑似青竜壁の生命線

입니다.

**Comment by ForestBurn** [comment]
위치는 Supersoldier Rising과 공유합니다.

사족이지만, 한국어 번역에서도 삼각형 표시를 추가해주실 수 있나요?

**Comment by kshman** [comment]
안녕하세요. 빈곳을 찾아주셔서 고맙습니다 😭

 추가해놨고 #50, 아마도 플러그인을 재실행하면 데이터 업데이트가 될...겁니다..로 알고 있는데
안되면 Data 디렉토리 내용을 받아서 덮어...써주세요 😭😭😭

고맙습니다 🥰

**Comment by revi** [comment]
[데이터 업데이트 가이드](https://revi.wiki/wiki/게임:파이널_판타지_14/미터기/매칭_알림/커스텀_패킷#신패치)를... 이번 5.55 하면서 적어놓긴 했습니다... 업데이트 순서가 드롭다운에서 뭔가를 선택해야 데이터가 업데이트 되는 것 같더라고요.

**Comment by ForestBurn** [comment]
빠른 적용 및 패치 감사합니다. 로그 상에선 이상 없이 작동하는 것을 확인했으나, 윗분의 가이드를 아무리 따라해도 적용이 되지 않아 json 파일을 다운받아 적용시켰습니다..

![이미지_2021-11-08_110355](https://user-images.githubusercontent.com/30828636/140673179-b9dbf7bd-8963-44c9-81ad-77e6a17af2c3.png)

**Comment by kshman** [comment]
잘되니 다행입니다. 🥰
업데이트는 확인해볼께요.  😱

딱히 추가할게 없으면 이 이슈는 닫는게 좋겠습니다 😊

**Comment by kshman** [comment]
아... 죄송합니다. 데이터 한번 더 업뎃하셔야할 수도 있겠네요;
검색하다 어느분이 자드놀 한국말 목록을 작성해두신게 있어서
옮겨 적고 있습니다. 😫

**Comment by kshman** [comment]
#51 
![image](https://user-images.githubusercontent.com/7216647/140682573-fd112d81-9903-4678-a665-908c14b3817a.png)
한글로 편하게 해보세요

DcDuty-Korean.json 갱신하면 됩니다..... 😭

**Comment by ForestBurn** [comment]
개인적으로 조사하고 한글화해서 썼는데, 감사합니다! 이슈는 닫겠습니다!
