### ISSUE TITLE
Korean 5.57 Packet

### ISSUE THREAD

**Issue by ForestBurn** [kshman/DutyContent#54]
OpFate=214
OpDuty=236
OpMatch=527
OpInstance=599
OpZone=785
OpSouthernBozja=277
입니다

**Comment by kshman** [comment]
적용할께요 조금만 기다려주세요.

저번에 9900원에 만든 계정이 끝나서 업뎃이 있었는지도 몰랐네요

**Comment by kshman** [comment]
적용했습니다. 고맙습니다 🥰
