### ISSUE TITLE
Ping on Korean client

### ISSUE THREAD

**Issue by kshman** [kshman/DutyContent#7]
Ping function doesn't works on Korean client

---
Oops
Anyway note

**Comment by kshman** [comment]
Lobby server: 183.111.189.3
World server: 183.111.189.42

Ping failed. Do not accept ping signal.
Probably blocked by provider.

**Comment by Jaehyuk-Lee** [comment]
핑을 왜 막아놨대요 ㅠㅠ 클라이언트에도 표시 안돼서 확인할 방법이 따로 없는데

**Comment by kshman** [comment]
헉... 그러게요
주소 얻으려고 시간들여 설치했는데, 막혀있더라구요. 😭

**Comment by Jaehyuk-Lee** [comment]
아 그러고보니 미꾸라지 VPN에서는 게임 서버 응답속도 측정이 되던데 어떻게 하는걸까요 ㅋㅋ
